#version 450

layout (local_size_x = 16, local_size_y = 16) in;
layout (binding = 0) uniform sampler2D input_image;
layout (binding = 1, rgba8) uniform writeonly image2D output_image;
layout(std430, binding = 2) buffer luma_buf {
    float luma[3];
};

void main()
{	
    vec2 image_dim = textureSize(input_image, 0);
    vec4 res = texture(input_image, vec2(gl_GlobalInvocationID.xy/image_dim));

    float luminance = res.r * luma[0] +
                      res.g * luma[1] +
                      res.b * luma[2];

    res.rgb = vec3(luminance);

    imageStore(output_image, ivec2(gl_GlobalInvocationID.xy), res);
}
