#version 450

layout (local_size_x = 16, local_size_y = 16) in;
layout (binding = 0, rgba8) uniform readonly  image2D input_image0;
layout (binding = 1, rgba8) uniform readonly  image2D input_image1;
layout (binding = 2, rgba8) uniform writeonly image2D output_image;

layout(binding = 4) uniform data {
    float _rf_time;
};

void main()
{	

    float _rf_time = 0.0;
    //float center_x = imageSize(input_image0).x/2;
    float center_x = imageSize(input_image0).x*(0.5*sin(_rf_time)+0.5);
    vec4 pixel = vec4(0);

    if(gl_GlobalInvocationID.x > center_x) {
        pixel = imageLoad(input_image0, ivec2(gl_GlobalInvocationID.xy));
    }
    else {
        pixel = imageLoad(input_image1, ivec2(gl_GlobalInvocationID.xy));
    }

    imageStore(output_image, ivec2(gl_GlobalInvocationID.xy), pixel);
}
